services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: easy_go_docs
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d easy_go_docs"]
      interval: 5s
      timeout: 3s
      retries: 10

  migrations:
    image: ghcr.io/kukymbr/goose-docker:3.24.3
    environment:
      - GOOSE_DRIVER=postgres
      - GOOSE_DBSTRING=host=db port=5432 user=app password=pass dbname=easy_go_docs
    volumes:
      - ./migrations:/migrations

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_DSN: "postgres://app:pass@db:5432/easy_go_docs?sslmode=disable"
      JWT_SECRET: "l5VwxuCXfmJ3G8vn2rzEo+UHar86kIb4CLW7mUqMlvM="
    ports:
      - "8080:8080"

volumes:
  pgdata:
