// Code generated by http://github.com/gojuno/minimock (v3.4.5). DO NOT EDIT.

package mocks

//go:generate minimock -i github.com/66gu1/easygodocs/internal/app/auth.TokenCodec -o token_codec_mock.go -n TokenCodecMock -p mocks

import (
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	"github.com/golang-jwt/jwt/v5"
)

// TokenCodecMock implements mm_auth.TokenCodec
type TokenCodecMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcGenerateToken          func(claims jwt.Claims) (s1 string, err error)
	funcGenerateTokenOrigin    string
	inspectFuncGenerateToken   func(claims jwt.Claims)
	afterGenerateTokenCounter  uint64
	beforeGenerateTokenCounter uint64
	GenerateTokenMock          mTokenCodecMockGenerateToken
}

// NewTokenCodecMock returns a mock for mm_auth.TokenCodec
func NewTokenCodecMock(t minimock.Tester) *TokenCodecMock {
	m := &TokenCodecMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.GenerateTokenMock = mTokenCodecMockGenerateToken{mock: m}
	m.GenerateTokenMock.callArgs = []*TokenCodecMockGenerateTokenParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mTokenCodecMockGenerateToken struct {
	optional           bool
	mock               *TokenCodecMock
	defaultExpectation *TokenCodecMockGenerateTokenExpectation
	expectations       []*TokenCodecMockGenerateTokenExpectation

	callArgs []*TokenCodecMockGenerateTokenParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// TokenCodecMockGenerateTokenExpectation specifies expectation struct of the TokenCodec.GenerateToken
type TokenCodecMockGenerateTokenExpectation struct {
	mock               *TokenCodecMock
	params             *TokenCodecMockGenerateTokenParams
	paramPtrs          *TokenCodecMockGenerateTokenParamPtrs
	expectationOrigins TokenCodecMockGenerateTokenExpectationOrigins
	results            *TokenCodecMockGenerateTokenResults
	returnOrigin       string
	Counter            uint64
}

// TokenCodecMockGenerateTokenParams contains parameters of the TokenCodec.GenerateToken
type TokenCodecMockGenerateTokenParams struct {
	claims jwt.Claims
}

// TokenCodecMockGenerateTokenParamPtrs contains pointers to parameters of the TokenCodec.GenerateToken
type TokenCodecMockGenerateTokenParamPtrs struct {
	claims *jwt.Claims
}

// TokenCodecMockGenerateTokenResults contains results of the TokenCodec.GenerateToken
type TokenCodecMockGenerateTokenResults struct {
	s1  string
	err error
}

// TokenCodecMockGenerateTokenOrigins contains origins of expectations of the TokenCodec.GenerateToken
type TokenCodecMockGenerateTokenExpectationOrigins struct {
	origin       string
	originClaims string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGenerateToken *mTokenCodecMockGenerateToken) Optional() *mTokenCodecMockGenerateToken {
	mmGenerateToken.optional = true
	return mmGenerateToken
}

// Expect sets up expected params for TokenCodec.GenerateToken
func (mmGenerateToken *mTokenCodecMockGenerateToken) Expect(claims jwt.Claims) *mTokenCodecMockGenerateToken {
	if mmGenerateToken.mock.funcGenerateToken != nil {
		mmGenerateToken.mock.t.Fatalf("TokenCodecMock.GenerateToken mock is already set by Set")
	}

	if mmGenerateToken.defaultExpectation == nil {
		mmGenerateToken.defaultExpectation = &TokenCodecMockGenerateTokenExpectation{}
	}

	if mmGenerateToken.defaultExpectation.paramPtrs != nil {
		mmGenerateToken.mock.t.Fatalf("TokenCodecMock.GenerateToken mock is already set by ExpectParams functions")
	}

	mmGenerateToken.defaultExpectation.params = &TokenCodecMockGenerateTokenParams{claims}
	mmGenerateToken.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGenerateToken.expectations {
		if minimock.Equal(e.params, mmGenerateToken.defaultExpectation.params) {
			mmGenerateToken.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGenerateToken.defaultExpectation.params)
		}
	}

	return mmGenerateToken
}

// ExpectClaimsParam1 sets up expected param claims for TokenCodec.GenerateToken
func (mmGenerateToken *mTokenCodecMockGenerateToken) ExpectClaimsParam1(claims jwt.Claims) *mTokenCodecMockGenerateToken {
	if mmGenerateToken.mock.funcGenerateToken != nil {
		mmGenerateToken.mock.t.Fatalf("TokenCodecMock.GenerateToken mock is already set by Set")
	}

	if mmGenerateToken.defaultExpectation == nil {
		mmGenerateToken.defaultExpectation = &TokenCodecMockGenerateTokenExpectation{}
	}

	if mmGenerateToken.defaultExpectation.params != nil {
		mmGenerateToken.mock.t.Fatalf("TokenCodecMock.GenerateToken mock is already set by Expect")
	}

	if mmGenerateToken.defaultExpectation.paramPtrs == nil {
		mmGenerateToken.defaultExpectation.paramPtrs = &TokenCodecMockGenerateTokenParamPtrs{}
	}
	mmGenerateToken.defaultExpectation.paramPtrs.claims = &claims
	mmGenerateToken.defaultExpectation.expectationOrigins.originClaims = minimock.CallerInfo(1)

	return mmGenerateToken
}

// Inspect accepts an inspector function that has same arguments as the TokenCodec.GenerateToken
func (mmGenerateToken *mTokenCodecMockGenerateToken) Inspect(f func(claims jwt.Claims)) *mTokenCodecMockGenerateToken {
	if mmGenerateToken.mock.inspectFuncGenerateToken != nil {
		mmGenerateToken.mock.t.Fatalf("Inspect function is already set for TokenCodecMock.GenerateToken")
	}

	mmGenerateToken.mock.inspectFuncGenerateToken = f

	return mmGenerateToken
}

// Return sets up results that will be returned by TokenCodec.GenerateToken
func (mmGenerateToken *mTokenCodecMockGenerateToken) Return(s1 string, err error) *TokenCodecMock {
	if mmGenerateToken.mock.funcGenerateToken != nil {
		mmGenerateToken.mock.t.Fatalf("TokenCodecMock.GenerateToken mock is already set by Set")
	}

	if mmGenerateToken.defaultExpectation == nil {
		mmGenerateToken.defaultExpectation = &TokenCodecMockGenerateTokenExpectation{mock: mmGenerateToken.mock}
	}
	mmGenerateToken.defaultExpectation.results = &TokenCodecMockGenerateTokenResults{s1, err}
	mmGenerateToken.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGenerateToken.mock
}

// Set uses given function f to mock the TokenCodec.GenerateToken method
func (mmGenerateToken *mTokenCodecMockGenerateToken) Set(f func(claims jwt.Claims) (s1 string, err error)) *TokenCodecMock {
	if mmGenerateToken.defaultExpectation != nil {
		mmGenerateToken.mock.t.Fatalf("Default expectation is already set for the TokenCodec.GenerateToken method")
	}

	if len(mmGenerateToken.expectations) > 0 {
		mmGenerateToken.mock.t.Fatalf("Some expectations are already set for the TokenCodec.GenerateToken method")
	}

	mmGenerateToken.mock.funcGenerateToken = f
	mmGenerateToken.mock.funcGenerateTokenOrigin = minimock.CallerInfo(1)
	return mmGenerateToken.mock
}

// When sets expectation for the TokenCodec.GenerateToken which will trigger the result defined by the following
// Then helper
func (mmGenerateToken *mTokenCodecMockGenerateToken) When(claims jwt.Claims) *TokenCodecMockGenerateTokenExpectation {
	if mmGenerateToken.mock.funcGenerateToken != nil {
		mmGenerateToken.mock.t.Fatalf("TokenCodecMock.GenerateToken mock is already set by Set")
	}

	expectation := &TokenCodecMockGenerateTokenExpectation{
		mock:               mmGenerateToken.mock,
		params:             &TokenCodecMockGenerateTokenParams{claims},
		expectationOrigins: TokenCodecMockGenerateTokenExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGenerateToken.expectations = append(mmGenerateToken.expectations, expectation)
	return expectation
}

// Then sets up TokenCodec.GenerateToken return parameters for the expectation previously defined by the When method
func (e *TokenCodecMockGenerateTokenExpectation) Then(s1 string, err error) *TokenCodecMock {
	e.results = &TokenCodecMockGenerateTokenResults{s1, err}
	return e.mock
}

// Times sets number of times TokenCodec.GenerateToken should be invoked
func (mmGenerateToken *mTokenCodecMockGenerateToken) Times(n uint64) *mTokenCodecMockGenerateToken {
	if n == 0 {
		mmGenerateToken.mock.t.Fatalf("Times of TokenCodecMock.GenerateToken mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGenerateToken.expectedInvocations, n)
	mmGenerateToken.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGenerateToken
}

func (mmGenerateToken *mTokenCodecMockGenerateToken) invocationsDone() bool {
	if len(mmGenerateToken.expectations) == 0 && mmGenerateToken.defaultExpectation == nil && mmGenerateToken.mock.funcGenerateToken == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGenerateToken.mock.afterGenerateTokenCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGenerateToken.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GenerateToken implements mm_auth.TokenCodec
func (mmGenerateToken *TokenCodecMock) GenerateToken(claims jwt.Claims) (s1 string, err error) {
	mm_atomic.AddUint64(&mmGenerateToken.beforeGenerateTokenCounter, 1)
	defer mm_atomic.AddUint64(&mmGenerateToken.afterGenerateTokenCounter, 1)

	mmGenerateToken.t.Helper()

	if mmGenerateToken.inspectFuncGenerateToken != nil {
		mmGenerateToken.inspectFuncGenerateToken(claims)
	}

	mm_params := TokenCodecMockGenerateTokenParams{claims}

	// Record call args
	mmGenerateToken.GenerateTokenMock.mutex.Lock()
	mmGenerateToken.GenerateTokenMock.callArgs = append(mmGenerateToken.GenerateTokenMock.callArgs, &mm_params)
	mmGenerateToken.GenerateTokenMock.mutex.Unlock()

	for _, e := range mmGenerateToken.GenerateTokenMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.s1, e.results.err
		}
	}

	if mmGenerateToken.GenerateTokenMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGenerateToken.GenerateTokenMock.defaultExpectation.Counter, 1)
		mm_want := mmGenerateToken.GenerateTokenMock.defaultExpectation.params
		mm_want_ptrs := mmGenerateToken.GenerateTokenMock.defaultExpectation.paramPtrs

		mm_got := TokenCodecMockGenerateTokenParams{claims}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.claims != nil && !minimock.Equal(*mm_want_ptrs.claims, mm_got.claims) {
				mmGenerateToken.t.Errorf("TokenCodecMock.GenerateToken got unexpected parameter claims, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGenerateToken.GenerateTokenMock.defaultExpectation.expectationOrigins.originClaims, *mm_want_ptrs.claims, mm_got.claims, minimock.Diff(*mm_want_ptrs.claims, mm_got.claims))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGenerateToken.t.Errorf("TokenCodecMock.GenerateToken got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGenerateToken.GenerateTokenMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGenerateToken.GenerateTokenMock.defaultExpectation.results
		if mm_results == nil {
			mmGenerateToken.t.Fatal("No results are set for the TokenCodecMock.GenerateToken")
		}
		return (*mm_results).s1, (*mm_results).err
	}
	if mmGenerateToken.funcGenerateToken != nil {
		return mmGenerateToken.funcGenerateToken(claims)
	}
	mmGenerateToken.t.Fatalf("Unexpected call to TokenCodecMock.GenerateToken. %v", claims)
	return
}

// GenerateTokenAfterCounter returns a count of finished TokenCodecMock.GenerateToken invocations
func (mmGenerateToken *TokenCodecMock) GenerateTokenAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGenerateToken.afterGenerateTokenCounter)
}

// GenerateTokenBeforeCounter returns a count of TokenCodecMock.GenerateToken invocations
func (mmGenerateToken *TokenCodecMock) GenerateTokenBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGenerateToken.beforeGenerateTokenCounter)
}

// Calls returns a list of arguments used in each call to TokenCodecMock.GenerateToken.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGenerateToken *mTokenCodecMockGenerateToken) Calls() []*TokenCodecMockGenerateTokenParams {
	mmGenerateToken.mutex.RLock()

	argCopy := make([]*TokenCodecMockGenerateTokenParams, len(mmGenerateToken.callArgs))
	copy(argCopy, mmGenerateToken.callArgs)

	mmGenerateToken.mutex.RUnlock()

	return argCopy
}

// MinimockGenerateTokenDone returns true if the count of the GenerateToken invocations corresponds
// the number of defined expectations
func (m *TokenCodecMock) MinimockGenerateTokenDone() bool {
	if m.GenerateTokenMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GenerateTokenMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GenerateTokenMock.invocationsDone()
}

// MinimockGenerateTokenInspect logs each unmet expectation
func (m *TokenCodecMock) MinimockGenerateTokenInspect() {
	for _, e := range m.GenerateTokenMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to TokenCodecMock.GenerateToken at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGenerateTokenCounter := mm_atomic.LoadUint64(&m.afterGenerateTokenCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GenerateTokenMock.defaultExpectation != nil && afterGenerateTokenCounter < 1 {
		if m.GenerateTokenMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to TokenCodecMock.GenerateToken at\n%s", m.GenerateTokenMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to TokenCodecMock.GenerateToken at\n%s with params: %#v", m.GenerateTokenMock.defaultExpectation.expectationOrigins.origin, *m.GenerateTokenMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGenerateToken != nil && afterGenerateTokenCounter < 1 {
		m.t.Errorf("Expected call to TokenCodecMock.GenerateToken at\n%s", m.funcGenerateTokenOrigin)
	}

	if !m.GenerateTokenMock.invocationsDone() && afterGenerateTokenCounter > 0 {
		m.t.Errorf("Expected %d calls to TokenCodecMock.GenerateToken at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GenerateTokenMock.expectedInvocations), m.GenerateTokenMock.expectedInvocationsOrigin, afterGenerateTokenCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *TokenCodecMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockGenerateTokenInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *TokenCodecMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *TokenCodecMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockGenerateTokenDone()
}
