name: CI
on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
          cache: true

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --build-tags testutil ./...

      - name: Run tests with coverage
        run: |
          make cover
          go tool cover -func=coverage.out | tail -1

      - name: govulncheck
        uses: golang/govulncheck-action@v1
        with:
          go-version-input: '1.22'
          packages: ./...

      # Артефакты (не обязательно, но удобно приложить coverage)
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage.out
          path: coverage.out
